name: Vacancy Monitor

on:
  schedule:
    # Cron syntax: "*/10 * * * *" means every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check_vacancies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run the script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
          CHECK_INTERVAL: ${{ secrets.CHECK_INTERVAL }}
        run: python your_script.py
